name: Andrey Kislyuk
masthead_title: Andrey Kislyuk - personal website
title: Andrey Kislyuk - personal website
subtitle: Subtitle
logo: https://avatars1.githubusercontent.com/u/862013
repository: kislyuk
breadcrumbs: true
email: kislyuk@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://kislyuk.com"
twitter_username: akislyuk
github_username:  kislyuk
twitter: "akislyuk"
# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.20.2"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

#theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

author:
  name             : "Andrey Kislyuk"
  avatar           : https://avatars1.githubusercontent.com/u/862013
  bio              : "BIO GOES HERE"
  location         : "San Francisco"
  email            : kislyuk@gmail.com
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:kislyuk@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://kislyuk.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/akislyuk"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/kislyuk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kislyuk"
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:kislyuk@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://kislyuk.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/akislyuk"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/kislyuk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kislyuk"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true

# Markdown Processing
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

